Remove gulp
lavalibs/discord.js pull request #2
Opened 2020-05-08 18:44 UTC by kuskoman

+ Remove gulpfile and gulp related dependencies
+ Update prepare script and add build script
+ Generate typings in same directory as other files

2020-05-08 19:32 UTC, appellation approved these changes

2020-05-14 08:25 UTC, DevYukine requested changes
please do not edit the tsconfig and change styling for no reason in there

2020-05-14 08:25 UTC, DevYukine commented on tsconfig.json
> -    "declarationDir": "./dist/typings",
why was this removed?

2020-05-14 08:25 UTC, DevYukine commented on tsconfig.json
> +    "outDir": "./dist/" /* Redirect output structure to the directory. */,
why did you move the comma?

2020-05-14 08:25 UTC, DevYukine commented on tsconfig.json
> +    "strict": true /* Enable all strict type-checking options. */,
same as above

2020-05-14 10:34 UTC, kuskoman commented on tsconfig.json
> -    "declarationDir": "./dist/typings",
Keeping typings folder for one file seems unreasonable, but ok, i can revert it back

2020-05-14 10:34 UTC, kuskoman commented on tsconfig.json
> +    "outDir": "./dist/" /* Redirect output structure to the directory. */,
IDE auto formatting

2020-05-27 23:45 UTC, closed without merging